/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/model`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pollyline`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/cloudinary/driverImage`; params?: Router.UnknownInputParams; } | { pathname: `/cloudinary/userImage`; params?: Router.UnknownInputParams; } | { pathname: `/pages/driverdashboard`; params?: Router.UnknownInputParams; } | { pathname: `/pages/driverRegister`; params?: Router.UnknownInputParams; } | { pathname: `/pages/driverResponse`; params?: Router.UnknownInputParams; } | { pathname: `/pages/searchedRides`; params?: Router.UnknownInputParams; } | { pathname: `/pages/signup`; params?: Router.UnknownInputParams; } | { pathname: `/pages/userdashboard`; params?: Router.UnknownInputParams; } | { pathname: `/pages/userRegister`; params?: Router.UnknownInputParams; } | { pathname: `/socket/socket`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/model`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/pollyline`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/cloudinary/driverImage`; params?: Router.UnknownOutputParams; } | { pathname: `/cloudinary/userImage`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/driverdashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/driverRegister`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/driverResponse`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/searchedRides`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/userdashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/userRegister`; params?: Router.UnknownOutputParams; } | { pathname: `/socket/socket`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/model${`?${string}` | `#${string}` | ''}` | `/../components/pollyline${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/cloudinary/driverImage${`?${string}` | `#${string}` | ''}` | `/cloudinary/userImage${`?${string}` | `#${string}` | ''}` | `/pages/driverdashboard${`?${string}` | `#${string}` | ''}` | `/pages/driverRegister${`?${string}` | `#${string}` | ''}` | `/pages/driverResponse${`?${string}` | `#${string}` | ''}` | `/pages/searchedRides${`?${string}` | `#${string}` | ''}` | `/pages/signup${`?${string}` | `#${string}` | ''}` | `/pages/userdashboard${`?${string}` | `#${string}` | ''}` | `/pages/userRegister${`?${string}` | `#${string}` | ''}` | `/socket/socket${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/model`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pollyline`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/cloudinary/driverImage`; params?: Router.UnknownInputParams; } | { pathname: `/cloudinary/userImage`; params?: Router.UnknownInputParams; } | { pathname: `/pages/driverdashboard`; params?: Router.UnknownInputParams; } | { pathname: `/pages/driverRegister`; params?: Router.UnknownInputParams; } | { pathname: `/pages/driverResponse`; params?: Router.UnknownInputParams; } | { pathname: `/pages/searchedRides`; params?: Router.UnknownInputParams; } | { pathname: `/pages/signup`; params?: Router.UnknownInputParams; } | { pathname: `/pages/userdashboard`; params?: Router.UnknownInputParams; } | { pathname: `/pages/userRegister`; params?: Router.UnknownInputParams; } | { pathname: `/socket/socket`; params?: Router.UnknownInputParams; };
    }
  }
}
